package newgen.presentation.component;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.AttributeSet;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyleContext;
import newgen.presentation.NewGenMain;
import org.jivesoftware.smack.Chat;
import org.jivesoftware.smack.ChatManager;
import org.jivesoftware.smack.ConnectionConfiguration;
import org.jivesoftware.smack.MessageListener;
import org.jivesoftware.smack.XMPPConnection;
import org.jivesoftware.smack.XMPPException;
import org.jivesoftware.smack.packet.Message;
import org.jivesoftware.smack.packet.Presence;
import org.jivesoftware.smack.proxy.ProxyInfo;
import org.json.JSONException;
import org.json.JSONObject;

/**
 *
 * @author siddartha
 */
public class ChatIF extends javax.swing.JFrame {

    Chat chat = null;

    private final Color cColor = new Color(177, 0, 0);

    private final Color nglColor = new Color(0, 177, 0);

    /** Creates new form ChatIF */
    private String username = "";

    private String password = "";

    private static ChatIF thisInstance;

    XMPPConnection connection = null;

    private ChatIF() {
        initComponents();
        jDialog1.setSize(425, 309);
        jDialog1.setLocation(NewGenMain.getAppletInstance().getLocation(425, 309));
        tfProxyHost.setText(NGLPreferences.getUserRoot().get("GProxyHost", ""));
        tfProxyPort.setText(NGLPreferences.getUserRoot().get("GProxyPort", ""));
        tfProxyUserName.setText(NGLPreferences.getUserRoot().get("GProxyUserName", ""));
        tfProxyPassword.setText(NGLPreferences.getUserRoot().get("GProxPassword", ""));
        setSize(609, 309);
        setVisible(true);
        tfUsername.setText(NGLPreferences.getUserRoot().get("GoogleUserName", ""));
    }

    public static ChatIF getInstance() {
        if (thisInstance == null) {
            thisInstance = new ChatIF();
        }
        return thisInstance;
    }

    public void connect(String username, String password) {
        ConnectionConfiguration connConfig = null;
        if (tfProxyUserName.getText().trim().equals("")) {
            connConfig = new ConnectionConfiguration("talk.google.com", 5222, "gmail.com");
        } else {
            ProxyInfo pi = new ProxyInfo(ProxyInfo.ProxyType.HTTP, tfProxyHost.getText(), Integer.parseInt(tfProxyPort.getText()), tfProxyUserName.getText(), String.valueOf(tfProxyPassword.getPassword()));
            connConfig = new ConnectionConfiguration("talk.google.com", 5222, "gmail.com", pi);
        }
        connection = new XMPPConnection(connConfig);
        try {
            connection.connect();
            System.out.println("Connected to " + connection.getHost());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Unable to connect to Google talk");
            jButton2.setEnabled(true);
            jButton3.setEnabled(false);
        }
        try {
            connection.login(username, password);
            System.out.println("Logged in as " + connection.getUser());
            Presence presence = new Presence(Presence.Type.available);
            connection.sendPacket(presence);
            jButton1.setEnabled(true);
        } catch (Exception ex) {
            jLabel2.setText("INVALID login details for " + username);
            JOptionPane.showMessageDialog(null, "Google talk authentication failed, this may be due to Internet failure or wrong user name and password");
            jButton1.setEnabled(false);
            jButton2.setEnabled(true);
            jButton3.setEnabled(false);
        }
        ChatManager chatmanager = connection.getChatManager();
        Chat chat = chatmanager.createChat("ngl.atyourservice@gmail.com", new MessageListener() {

            @Override
            public void processMessage(Chat chat, Message msg) {
                jTextArea1.append("Verus NGL support said: " + msg.getBody() + "\n");
            }
        });
        this.chat = chat;
        jButton2.setEnabled(false);
        jLabel2.setText("You are logged in as " + username);
        NGLPreferences.getUserRoot().put("GoogleUserName", tfUsername.getText());
        jButton3.setEnabled(true);
        jTextField1.requestFocus();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        jDialog1 = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        bnSetProxy = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tfProxyHost = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfProxyPort = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfProxyUserName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfProxyPassword = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfPassword = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bnSetProxy.setMnemonic('s');
        bnSetProxy.setText("Set Proxy");
        bnSetProxy.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnSetProxyActionPerformed(evt);
            }
        });
        jPanel6.add(bnSetProxy);
        jDialog1.getContentPane().add(jPanel6, java.awt.BorderLayout.PAGE_END);
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Proxy details"));
        jPanel7.setLayout(new java.awt.GridBagLayout());
        jLabel5.setText("Host");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel7.add(jLabel5, gridBagConstraints);
        tfProxyHost.setColumns(15);
        jPanel7.add(tfProxyHost, new java.awt.GridBagConstraints());
        jLabel6.setText("Port");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel7.add(jLabel6, gridBagConstraints);
        tfProxyPort.setColumns(15);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        jPanel7.add(tfProxyPort, gridBagConstraints);
        jLabel7.setText("User name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel7.add(jLabel7, gridBagConstraints);
        tfProxyUserName.setColumns(15);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        jPanel7.add(tfProxyUserName, gridBagConstraints);
        jLabel8.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel7.add(jLabel8, gridBagConstraints);
        tfProxyPassword.setColumns(15);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        jPanel7.add(tfProxyPassword, gridBagConstraints);
        jDialog1.getContentPane().add(jPanel7, java.awt.BorderLayout.CENTER);
        setTitle("Chat with Verus NewGenLib Support Team");
        jTextField1.setColumns(25);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jButton1.setMnemonic('s');
        jButton1.setText("Send");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);
        jPanel2.setLayout(new java.awt.BorderLayout());
        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setFont(new java.awt.Font("Ubuntu", 1, 15));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);
        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Google login"));
        jPanel4.setLayout(new java.awt.GridBagLayout());
        jLabel3.setText("User name:");
        jPanel4.add(jLabel3, new java.awt.GridBagConstraints());
        tfUsername.setColumns(10);
        jPanel4.add(tfUsername, new java.awt.GridBagConstraints());
        jLabel4.setText("Password");
        jPanel4.add(jLabel4, new java.awt.GridBagConstraints());
        tfPassword.setColumns(10);
        jPanel4.add(tfPassword, new java.awt.GridBagConstraints());
        jButton2.setMnemonic('c');
        jButton2.setText("Connect");
        jButton2.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new java.awt.GridBagConstraints());
        jButton3.setMnemonic('d');
        jButton3.setText("Disconnect");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3, new java.awt.GridBagConstraints());
        jButton4.setText("Set proxy");
        jButton4.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(jButton4, gridBagConstraints);
        jPanel3.add(jPanel4);
        jLabel1.setForeground(new java.awt.Color(0, 0, 165));
        jPanel5.add(jLabel1);
        jLabel2.setForeground(java.awt.Color.blue);
        jPanel5.add(jLabel2);
        jPanel3.add(jPanel5);
        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);
        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);
        pack();
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        if (!jTextField1.getText().trim().equals("")) {
            try {
                Message msg = new Message("ngl.atyourservice@gmail.com", Message.Type.chat);
                msg.setBody("You said: " + jTextField1.getText());
                chat.sendMessage(msg);
                jTextArea1.append(msg.getBody() + "\n");
                jTextField1.setText("");
            } catch (XMPPException e) {
                System.out.println("Failed to send message");
                jButton2.setEnabled(true);
                jButton3.setEnabled(false);
            }
        }
    }

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
        jButton1.doClick();
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            this.username = tfUsername.getText();
            this.password = String.valueOf(tfPassword.getPassword());
            connect(username, password);
        } catch (Exception ex) {
        }
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
        jButton2.setEnabled(true);
        jButton1.setEnabled(false);
        jButton3.setEnabled(false);
        jLabel2.setText("You are currently disconnected");
        connection.disconnect();
    }

    private void bnSetProxyActionPerformed(java.awt.event.ActionEvent evt) {
        NGLPreferences.getUserRoot().put("GProxyHost", tfProxyHost.getText());
        NGLPreferences.getUserRoot().put("GProxyPort", tfProxyPort.getText());
        NGLPreferences.getUserRoot().put("GProxyUserName", tfProxyUserName.getText());
        NGLPreferences.getUserRoot().put("GProxPassword", tfProxyPassword.getText());
        jDialog1.dispose();
    }

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
        jDialog1.setVisible(true);
    }

    private javax.swing.JButton bnSetProxy;

    private javax.swing.JButton jButton1;

    private javax.swing.JButton jButton2;

    private javax.swing.JButton jButton3;

    private javax.swing.JButton jButton4;

    private javax.swing.JDialog jDialog1;

    private javax.swing.JLabel jLabel1;

    private javax.swing.JLabel jLabel2;

    private javax.swing.JLabel jLabel3;

    private javax.swing.JLabel jLabel4;

    private javax.swing.JLabel jLabel5;

    private javax.swing.JLabel jLabel6;

    private javax.swing.JLabel jLabel7;

    private javax.swing.JLabel jLabel8;

    private javax.swing.JPanel jPanel1;

    private javax.swing.JPanel jPanel2;

    private javax.swing.JPanel jPanel3;

    private javax.swing.JPanel jPanel4;

    private javax.swing.JPanel jPanel5;

    private javax.swing.JPanel jPanel6;

    private javax.swing.JPanel jPanel7;

    private javax.swing.JScrollPane jScrollPane1;

    private javax.swing.JTextArea jTextArea1;

    private javax.swing.JTextField jTextField1;

    private javax.swing.JPasswordField tfPassword;

    private javax.swing.JTextField tfProxyHost;

    private javax.swing.JPasswordField tfProxyPassword;

    private javax.swing.JTextField tfProxyPort;

    private javax.swing.JTextField tfProxyUserName;

    private javax.swing.JTextField tfUsername;
}
