package com.jjcp;

import java.awt.Component;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.geom.AffineTransform;
import java.awt.image.AffineTransformOp;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.io.InputStream;
import java.net.URL;
import java.net.URLConnection;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author  Juan Jose Cerme�o Portet jjcermeno@turyon.com
 */
public class ImagePanel extends javax.swing.JPanel {

    Vector urls;

    SelectorClientView selectorClient;

    /** Creates new form ImagePanel */
    public ImagePanel() {
        initComponents();
    }

    public void setSelectorClient(SelectorClientView sc) {
        selectorClient = sc;
    }

    public SelectorClientView getSelectorClient() {
        return selectorClient;
    }

    public void setURLs(Vector urls) {
        this.urls = urls;
        addButtons();
    }

    public Vector getURLs() {
        return this.urls;
    }

    public void addButton(Component comp) {
        jPanel1.add(comp);
    }

    public static BufferedImage resizeAnImage(BufferedImage in, double scale) {
        AffineTransform tx = AffineTransform.getScaleInstance(scale, scale);
        AffineTransformOp op = new AffineTransformOp(tx, AffineTransformOp.TYPE_BICUBIC);
        return op.filter(in, null);
    }

    public void addButtons() {
        BufferedImage bufImage = null;
        BufferedImage bufImage1 = null;
        for (int i = 0; i < urls.size(); i++) {
            String url = (String) urls.elementAt(i);
            if (url.contains(java.util.ResourceBundle.getBundle("com/jjcp/resources/Strings").getString("IHERETRIEVEDOCUMENT"))) {
                return;
            }
            try {
                URL url1 = new URL(url);
                URLConnection conn = null;
                conn = url1.openConnection();
                InputStream in = conn.getInputStream();
                in.close();
                bufImage = ImageIO.read(url1);
                bufImage1 = resizeAnImage(bufImage, 0.25);
                ImageIcon icon = new ImageIcon(bufImage1);
                ImageButton imageButton = new ImageButton(icon, this, i);
                imageButton.setIndex(i);
                jPanel1.add(imageButton);
                jPanel1.setPreferredSize(new Dimension(imageButton.getWidth() * urls.size(), imageButton.getHeight() + 20));
            } catch (Exception exception) {
                exception.printStackTrace();
            }
        }
        this.setVisible(true);
        this.repaint();
    }

    public static void main(String[] args) throws IOException {
        String url = new String(java.util.ResourceBundle.getBundle("com/jjcp/resources/Strings").getString("HTTP://BLOGS.SUN.COM/JAG/RESOURCE/JAGHEADSHOT-SMALL.JPG"));
        Vector urls = new Vector();
        urls.addElement(url);
        urls.addElement(url);
        urls.addElement(url);
        urls.addElement(url);
        urls.addElement(url);
        JFrame f = new JFrame();
        Container cp = f.getContentPane();
        ImagePanel imagePanel = new ImagePanel();
        cp.add(imagePanel);
        imagePanel.setURLs(urls);
        f.setSize(300, 80);
        f.pack();
        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        f.setLocationRelativeTo(null);
        f.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        setName("Form");
        setLayout(new java.awt.BorderLayout());
        jScrollPane1.setName("jScrollPane1");
        jPanel1.setName("jPanel1");
        jScrollPane1.setViewportView(jPanel1);
        add(jScrollPane1, java.awt.BorderLayout.PAGE_START);
    }

    private javax.swing.JPanel jPanel1;

    private javax.swing.JScrollPane jScrollPane1;
}
