package csa.jportal.cardset;

import csa.jportal.JPortalView;
import csa.jportal.ai.enhancedAI.enhancedHints.AIEnhancedCardHints;
import csa.jportal.ai.enhancedAI.enhancedHints.AIEnhancedHint;
import csa.jportal.ai.enhancedAI.enhancedHints.AIEnhancedHintData;
import csa.jportal.ai.standardAI.hints.AICardHints;
import csa.jportal.ai.standardAI.hints.AIHintsData;
import csa.jportal.card.Card;
import csa.jportal.card.CardSituation;
import csa.jportal.config.Configuration;
import csa.jportal.config.Logable;
import csa.jportal.gui.Windowable;
import csa.jportal.script.ScriptData;
import csa.jportal.script.ScriptDataPool;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileOutputStream;
import java.io.InputStreamReader;
import java.net.InetSocketAddress;
import java.net.Proxy;
import java.net.URL;
import java.net.URLConnection;
import java.util.Collection;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.Set;
import java.util.Vector;
import javax.swing.AbstractButton;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JRadioButton;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author malban
 */
public class ImportSpecialPanel extends javax.swing.JPanel implements Windowable, Runnable {

    private JPortalView mParent = null;

    private javax.swing.JMenuItem mParentMenuItem = null;

    public static final Proxy.Type[] PROXY_TYPES = Proxy.Type.values();

    private int mProxyType = 0;

    private CardSet mLoadedCardSet = new CardSet();

    public void closing() {
    }

    public void setParentWindow(JPortalView jpv) {
        mParent = jpv;
    }

    public void setMenuItem(javax.swing.JMenuItem item) {
        mParentMenuItem = item;
        mParentMenuItem.setText("Import Gatherer-Set");
    }

    public javax.swing.JMenuItem getMenuItem() {
        return mParentMenuItem;
    }

    public javax.swing.JPanel getPanel() {
        return this;
    }

    /** Creates new form ImportSpecialPanel */
    public ImportSpecialPanel() {
        initComponents();
        jTextFieldBaseUrl.setText(Configuration.getConfiguration().getGathererBaseURL());
        jPanel4.removeAll();
        String[] text = { "No Proxy", "Http Proxy", "Socks Proxy" };
        for (int i = 0; i < PROXY_TYPES.length; i++) {
            JRadioButton rb = new JRadioButton(text[i]);
            final int t = i;
            rb.addChangeListener(new ChangeListener() {

                @Override
                public void stateChanged(ChangeEvent e) {
                    if (((AbstractButton) e.getSource()).isSelected()) {
                        mProxyType = t;
                        jTextFieldProxyURL.setEnabled(mProxyType != 0);
                        jTextFieldProxyPort.setEnabled(mProxyType != 0);
                    }
                }
            });
            buttonGroup1.add(rb);
            jPanel4.add(rb);
            if (i == 0) rb.setSelected(true);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {
        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButtonImport = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaOut = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCheckBoxImages = new javax.swing.JCheckBox();
        jCheckBoxJoin = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jTextFieldProxyURL = new javax.swing.JTextField();
        jTextFieldProxyPort = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jRadioButtonPType = new javax.swing.JRadioButton();
        jTextFieldBaseUrl = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabelImage = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jTabbedPane1.setName("jTabbedPane1");
        jPanel1.setName("jPanel1");
        jButtonImport.setText("Import all");
        jButtonImport.setName("jButtonImport");
        jButtonImport.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImportActionPerformed(evt);
            }
        });
        jPanel2.setName("jPanel2");
        jScrollPane1.setName("jScrollPane1");
        jTextAreaOut.setColumns(20);
        jTextAreaOut.setRows(5);
        jTextAreaOut.setName("jTextAreaOut");
        jScrollPane1.setViewportView(jTextAreaOut);
        jLabel1.setText("Log");
        jLabel1.setName("jLabel1");
        jLabel5.setText(" ");
        jLabel5.setName("jLabel5");
        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel2Layout.createSequentialGroup().addComponent(jLabel1).addGap(88, 88, 88).addComponent(jLabel5).addGap(435, 435, 435)).addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE));
        jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel2Layout.createSequentialGroup().addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel1).addComponent(jLabel5)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)));
        jLabel2.setText("<html> <H2>Import</h2> All sets currently found in the gatherer Database.<br> \n<p> <LI>If \"Images\" CheckBox is checked - all images found in the gatherer DB are also loaded - can take quite <b>some</b> time </LI></p> \n<p> <LI>If \"Join\" CheckBox is checked - JPortal tries to find all currently supported cards by JPortal (same cards in new sets that are included \nin JPortal suppored sets) are marked as supported. \n</LI></p> \n</html>");
        jLabel2.setName("jLabel2");
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jCheckBoxImages.setText("Import Images");
        jCheckBoxImages.setName("jCheckBoxImages");
        jCheckBoxJoin.setText("Join current JPortal implementations");
        jCheckBoxJoin.setName("jCheckBoxJoin");
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Proxy Settings"));
        jPanel3.setName("jPanel3");
        jTextFieldProxyURL.setText("Proxy Adress");
        jTextFieldProxyURL.setToolTipText("URL");
        jTextFieldProxyURL.setName("jTextFieldProxyURL");
        jTextFieldProxyPort.setText("Port Number");
        jTextFieldProxyPort.setToolTipText("Port");
        jTextFieldProxyPort.setName("jTextFieldProxyPort");
        jPanel4.setName("jPanel4");
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.Y_AXIS));
        jRadioButtonPType.setText("jRadioButton1");
        jRadioButtonPType.setName("jRadioButtonPType");
        jPanel4.add(jRadioButtonPType);
        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel3Layout.createSequentialGroup().addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jTextFieldProxyURL, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jTextFieldProxyPort, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap()));
        jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE).addGroup(jPanel3Layout.createSequentialGroup().addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jTextFieldProxyURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jTextFieldProxyPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addContainerGap()));
        jTextFieldBaseUrl.setToolTipText("At the time of Developement it is: \"http://gatherer.wizards.com/Pages/\"");
        jTextFieldBaseUrl.setName("jTextFieldBaseUrl");
        jLabel3.setText("Gatherer base URL");
        jLabel3.setName("jLabel3");
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setName("jPanel5");
        jLabelImage.setText(" ");
        jLabelImage.setName("jLabelImage");
        jLabel4.setText(" ");
        jLabel4.setName("jLabel4");
        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel5Layout.createSequentialGroup().addComponent(jLabelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap(44, Short.MAX_VALUE)));
        jPanel5Layout.setVerticalGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel5Layout.createSequentialGroup().addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false).addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(jLabelImage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)).addContainerGap(19, Short.MAX_VALUE)));
        jCheckBox1.setText("Find similar Cards");
        jCheckBox1.setEnabled(false);
        jCheckBox1.setName("jCheckBox1");
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel1Layout.createSequentialGroup().addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addGroup(jPanel1Layout.createSequentialGroup().addComponent(jLabel3).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jTextFieldBaseUrl)).addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jCheckBoxImages).addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addComponent(jButtonImport))).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE).addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jCheckBox1).addComponent(jCheckBoxJoin)))).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE).addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))).addContainerGap()));
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel3).addComponent(jTextFieldBaseUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jCheckBoxImages).addComponent(jCheckBoxJoin)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jCheckBox1).addComponent(jButtonImport)))).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel1Layout.createSequentialGroup().addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap()).addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))));
        jTabbedPane1.addTab("Import all known sets", jPanel1);
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jTabbedPane1));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jTabbedPane1));
    }

    private void jButtonImportActionPerformed(java.awt.event.ActionEvent evt) {
        jButtonImport.setEnabled(false);
        doImport();
    }

    private javax.swing.ButtonGroup buttonGroup1;

    private javax.swing.JButton jButtonImport;

    private javax.swing.JCheckBox jCheckBox1;

    private javax.swing.JCheckBox jCheckBoxImages;

    private javax.swing.JCheckBox jCheckBoxJoin;

    private javax.swing.JLabel jLabel1;

    private javax.swing.JLabel jLabel2;

    private javax.swing.JLabel jLabel3;

    private javax.swing.JLabel jLabel4;

    private javax.swing.JLabel jLabel5;

    private javax.swing.JLabel jLabelImage;

    private javax.swing.JPanel jPanel1;

    private javax.swing.JPanel jPanel2;

    private javax.swing.JPanel jPanel3;

    private javax.swing.JPanel jPanel4;

    private javax.swing.JPanel jPanel5;

    private javax.swing.JRadioButton jRadioButtonPType;

    private javax.swing.JScrollPane jScrollPane1;

    private javax.swing.JTabbedPane jTabbedPane1;

    private javax.swing.JTextArea jTextAreaOut;

    private javax.swing.JTextField jTextFieldBaseUrl;

    private javax.swing.JTextField jTextFieldProxyPort;

    private javax.swing.JTextField jTextFieldProxyURL;

    Vector<String> getSetNames() {
        Vector<String> ret = new Vector<String>();
        Proxy p = null;
        if (mProxyType == 0) p = Proxy.NO_PROXY; else {
            try {
                p = new Proxy(PROXY_TYPES[mProxyType], new InetSocketAddress(jTextFieldProxyURL.getText(), Integer.parseInt(jTextFieldProxyPort.getText())));
            } catch (Exception e) {
                e.printStackTrace();
                Configuration.getConfiguration().getDebugEntity().addLog(e, Logable.LOG_ERROR);
                return ret;
            }
        }
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            try {
                String baseUrl = jTextFieldBaseUrl.getText();
                URL url = new URL(baseUrl);
                URLConnection conn = url.openConnection(p);
                conn.setDoOutput(true);
                BufferedReader rd = new BufferedReader(new InputStreamReader(conn.getInputStream()));
                String line;
                boolean save = false;
                while ((line = rd.readLine()) != null) {
                    if (line.indexOf("Filter Card Set") != -1) save = true;
                    if (line.indexOf("Filter Card Type") != -1) save = false;
                    if (save) {
                        if (line.indexOf("<option value=\"") != -1) {
                            String name = line.substring(line.indexOf("\"") + 1, line.indexOf("\">"));
                            name = csa.util.UtilityString.fromXML(name);
                            if (name.trim().length() != 0) {
                                if (knownSets.get(name) == null) ret.addElement(name);
                            }
                        }
                    }
                }
                rd.close();
            } catch (Exception e) {
                e.printStackTrace();
                Configuration.getConfiguration().getDebugEntity().addLog(e, Logable.LOG_ERROR);
            }
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
        return ret;
    }

    private void importOneSet(String setName, Proxy p) {
        String setNameUrl = csa.util.UtilityString.replace(setName, " ", "%20");
        setName = csa.util.UtilityString.replace(setName, "\"", "");
        setName = csa.util.UtilityString.replace(setName, "'", "");
        setName = csa.util.UtilityString.replace(setName, "´", "");
        setName = csa.util.UtilityString.replace(setName, "`", "");
        setName = csa.util.UtilityString.replace(setName, ":", "");
        String base = jTextFieldBaseUrl.getText();
        Card.resetStatic();
        System.gc();
        mLoadedCardSet = new CardSet();
        mLoadedCardSet.getData().mOrigin = CardSet.GATHERER_IMPORTED;
        mLoadedCardSet.getData().mSetName = setName;
        try {
            String searcher = "Search/Default.aspx?output=spoiler&method=text&set=[%22" + setNameUrl + "%22] ";
            URL url = new URL(base + searcher);
            URLConnection conn = url.openConnection(p);
            conn.setDoOutput(true);
            BufferedReader rd = new BufferedReader(new InputStreamReader(conn.getInputStream()));
            String line;
            boolean save = false;
            String[] dontLike = { "<tr>", "</tr>", "<td", "</td>", "<table>", "</table>" };
            int NAME = 0;
            int COST = 1;
            int TYPE = 2;
            int POW = 3;
            int TEXT = 4;
            int RARITY = 5;
            String[] textTags = { "Name:", "Cost:", "Type:", "Pow/Tgh:", "Rules Text:", "Set/Rarity:" };
            Card card = new Card();
            int currentTag = -1;
            String dbg = "";
            while ((line = rd.readLine()) != null) {
                if (line.indexOf("class=\"textspoiler\"") != -1) save = true;
                if (line.indexOf("</div>") != -1) save = false;
                if (save) {
                    boolean goOn = true;
                    for (int i = 0; i < dontLike.length; i++) {
                        if (line.indexOf(dontLike[i]) != -1) {
                            goOn = false;
                            break;
                        }
                    }
                    if (goOn) {
                        for (int i = 0; i < textTags.length; i++) {
                            if (line.indexOf(textTags[i]) != -1) {
                                currentTag = i;
                                goOn = false;
                                break;
                            }
                        }
                    }
                    if (goOn) {
                        if (NAME == currentTag) {
                            dbg = "";
                            String id = line.substring(line.indexOf("multiverseid=") + 13);
                            id = id.substring(0, id.indexOf("\""));
                            String name = line.substring(line.indexOf(">") + 1);
                            name = name.substring(0, name.indexOf("<"));
                            card = new Card();
                            card.getData().setId(id);
                            card.getData().setCardName(name);
                            card.getData().setSetName(setName);
                            dbg += "Card: " + name + "(" + id + ")\n";
                            currentTag = -1;
                        }
                        if (COST == currentTag) {
                            String cost = line.trim();
                            cost = csa.util.UtilityString.replace(cost, "G", "{G}");
                            cost = csa.util.UtilityString.replace(cost, "B", "{B}");
                            cost = csa.util.UtilityString.replace(cost, "W", "{W}");
                            cost = csa.util.UtilityString.replace(cost, "R", "{R}");
                            cost = csa.util.UtilityString.replace(cost, "U", "{U}");
                            cost = csa.util.UtilityString.replace(cost, "X", "{X}");
                            cost = csa.util.UtilityString.replace(cost, "1", "{1}");
                            cost = csa.util.UtilityString.replace(cost, "2", "{2}");
                            cost = csa.util.UtilityString.replace(cost, "3", "{3}");
                            cost = csa.util.UtilityString.replace(cost, "4", "{4}");
                            cost = csa.util.UtilityString.replace(cost, "5", "{5}");
                            cost = csa.util.UtilityString.replace(cost, "6", "{6}");
                            cost = csa.util.UtilityString.replace(cost, "7", "{7}");
                            cost = csa.util.UtilityString.replace(cost, "8", "{8}");
                            cost = csa.util.UtilityString.replace(cost, "9", "{9}");
                            card.getData().setMana(cost);
                            dbg += "Cost: " + cost + "\n";
                            currentTag = -1;
                        }
                        if (TYPE == currentTag) {
                            String type = line.trim();
                            int typeEnd = -1;
                            int subtypeStart = -1;
                            for (int i = 0; i < type.length(); i++) {
                                if (((int) (type.charAt(i))) > 250) {
                                    typeEnd = i - 1;
                                    for (int c = i; c < type.length(); c++) {
                                        if (((int) (type.charAt(c))) == 32) {
                                            subtypeStart = c;
                                            break;
                                        }
                                    }
                                    break;
                                }
                            }
                            if (typeEnd != -1) {
                                card.getData().setType(type.substring(0, typeEnd).trim());
                                dbg += "Type: " + type.substring(0, typeEnd).trim() + " ";
                            } else {
                                card.getData().setType(type);
                                dbg += "Type: " + type + " ";
                            }
                            if (subtypeStart != -1) {
                                String subType = type.substring(subtypeStart).trim();
                                card.getData().setSubtype(subType.trim());
                                dbg += "SubType: " + subType.trim() + "\n";
                            }
                            currentTag = -1;
                        }
                        if (POW == currentTag) {
                            String powerToughness = line.trim();
                            if (powerToughness.length() == 0) {
                                card.getData().setPower("");
                                card.getData().setToughness("");
                            } else {
                                powerToughness = csa.util.UtilityString.replace(powerToughness, "(", "");
                                powerToughness = csa.util.UtilityString.replace(powerToughness, ")", "");
                                String power = powerToughness.substring(0, powerToughness.indexOf("/"));
                                String toughness = powerToughness.substring(powerToughness.indexOf("/") + 1);
                                card.getData().setPower(power);
                                card.getData().setToughness(toughness);
                            }
                            dbg += "Pow/Tough: " + card.getData().getPower() + "/" + card.getData().getToughness() + "\n";
                            currentTag = -1;
                        }
                        if (TEXT == currentTag) {
                            String text = line.trim();
                            text = csa.util.UtilityString.replace(text, "<br />", " ");
                            card.addText(text);
                        }
                        if (RARITY == currentTag) {
                            dbg += "Text: " + card.getText() + "\n";
                            String r = "";
                            String rarity = line.substring(line.indexOf(setName) + setName.length());
                            int l = rarity.length();
                            if (rarity.indexOf(",") != -1) l = rarity.indexOf(",");
                            rarity = rarity.substring(0, l);
                            if (rarity.indexOf("Common") != -1) r = "C";
                            if (rarity.indexOf("Uncommon") != -1) r = "U";
                            if (rarity.indexOf("Rare") != -1) r = "R";
                            if (rarity.indexOf("Land") != -1) r = "L";
                            card.getData().setRarity(r);
                            if (card.getType().equalsIgnoreCase("Basic Land")) {
                                if (card.getText().indexOf("{T}") == -1) card.addfText("{T}:");
                            }
                            dbg += "Rarity: " + r + "\n";
                            dbg += "----\n";
                            mLoadedCardSet.addCard(card);
                            currentTag = -1;
                            synchronized (this) {
                            }
                        }
                    }
                }
            }
            rd.close();
        } catch (Exception e) {
            e.printStackTrace();
            Configuration.getConfiguration().getDebugEntity().addLog(e, Logable.LOG_ERROR);
            return;
        }
        if (jCheckBoxImages.isSelected()) {
            String dirName = "sets" + File.separator + setName;
            File dir = new File(dirName);
            if (!dir.exists()) {
                try {
                    dir.mkdir();
                } catch (Throwable e) {
                    e.printStackTrace();
                    Configuration.getConfiguration().getDebugEntity().addLog(e, Logable.LOG_ERROR);
                }
            }
            mLoadedCardSet.getData().mImagePath = dirName;
            HashMap<String, String> imageUrls = new HashMap<String, String>();
            try {
                String secondBase = "Search/";
                String searcher = new String("Default.aspx?output=spoiler&method=visual&set=[%22" + setNameUrl + "%22] ");
                URL url = new URL(base + secondBase + searcher);
                URLConnection conn = url.openConnection(p);
                conn.setDoOutput(true);
                BufferedReader rd = new BufferedReader(new InputStreamReader(conn.getInputStream()));
                String line;
                boolean save = false;
                while ((line = rd.readLine()) != null) {
                    if (line.indexOf("class=\"visualspoiler\"") != -1) save = true;
                    if (line.indexOf("</div>") != -1) save = false;
                    if (save) {
                        if (line.indexOf("<img src=") != -1) {
                            line = line.substring(line.indexOf("<img src=") + "<img src=".length() + 1);
                            line = line.substring(0, line.indexOf("\""));
                            String id = line.substring(line.indexOf("=") + 1);
                            id = id.substring(0, id.indexOf("&"));
                            String imageUrl = csa.util.UtilityString.fromXML(line);
                            if (imageUrl.startsWith(".")) {
                                imageUrl = base + secondBase + imageUrl;
                            }
                            imageUrls.put(id, imageUrl);
                            synchronized (this) {
                                String dbg = "ID: " + id + " ImageUrl: " + imageUrl + " got!\n";
                                jTextAreaOut.insert(dbg, jTextAreaOut.getText().length());
                                jTextAreaOut.setCaretPosition(jTextAreaOut.getText().length() - dbg.length());
                                Configuration.getConfiguration().getLogEntity().addLog(dbg);
                            }
                        }
                    }
                }
                rd.close();
            } catch (Exception e) {
                e.printStackTrace();
                Configuration.getConfiguration().getDebugEntity().addLog(e, Logable.LOG_ERROR);
            }
            BufferedInputStream in;
            BufferedOutputStream out;
            Set entries = imageUrls.entrySet();
            Iterator it = entries.iterator();
            int c = 0;
            while (it.hasNext()) {
                Map.Entry entry = (Map.Entry) it.next();
                String imageUrl = (String) entry.getValue();
                String id = (String) entry.getKey();
                String imagePath = dirName + File.separator + id + ".jpg";
                File f = new File(imagePath);
                if (f.exists()) continue;
                try {
                    in = new BufferedInputStream(new URL(imageUrl).openConnection(p).getInputStream());
                    Image image = javax.imageio.ImageIO.read(in);
                    Icon i = new ImageIcon(image);
                    jLabelImage.setIcon(i);
                    out = new BufferedOutputStream(new FileOutputStream(f));
                    BufferedImage bimage = csa.util.UtilityImage.toBufferedImage(image);
                    if (bimage.getHeight() != 285) {
                        BufferedImage bimageCropped = bimage.getSubimage(11, 12, 200, 285);
                        Icon iCropped = new ImageIcon(bimageCropped);
                        jLabel4.setIcon(iCropped);
                        javax.imageio.ImageIO.write(bimageCropped, "jpg", f);
                    } else javax.imageio.ImageIO.write(bimage, "jpg", f);
                    in.close();
                    c++;
                    synchronized (this) {
                        String dbg = "(" + c + "/" + imageUrls.size() + ")Image successfully saved to: " + imagePath + "\n";
                        jTextAreaOut.insert(dbg, jTextAreaOut.getText().length());
                        try {
                            jTextAreaOut.setCaretPosition(jTextAreaOut.getText().length() - dbg.length());
                        } catch (Throwable e) {
                        }
                        Configuration.getConfiguration().getLogEntity().addLog(dbg);
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                    Configuration.getConfiguration().getDebugEntity().addLog(e, Logable.LOG_ERROR);
                }
            }
            jButtonImport.setEnabled(true);
            Card.addImagePathForSet(setName, dirName + File.separator);
            String dbg = "Import finished!\n";
            dbg = "\nImages and set are saved.";
            jTextAreaOut.insert(dbg, jTextAreaOut.getText().length());
            jTextAreaOut.setCaretPosition(jTextAreaOut.getText().length());
            Configuration.getConfiguration().getLogEntity().addLog(dbg);
        }
        mLoadedCardSet.getData().mClass = "MagicSets";
        mLoadedCardSet.getData().mName = setName;
        mLoadedCardSet.joinedSave();
    }

    public void run() {
        Proxy p = null;
        if (mProxyType == 0) p = Proxy.NO_PROXY; else {
            try {
                p = new Proxy(PROXY_TYPES[mProxyType], new InetSocketAddress(jTextFieldProxyURL.getText(), Integer.parseInt(jTextFieldProxyPort.getText())));
            } catch (Exception e) {
                e.printStackTrace();
                Configuration.getConfiguration().getDebugEntity().addLog(e, Logable.LOG_ERROR);
                return;
            }
        }
        int allNewKnown = 0;
        for (int i = 0; i < setNamesToImport.size(); i++) {
            String setName = setNamesToImport.elementAt(i);
            jLabel5.setText("Importing: " + setName + " (" + (i + 1) + "/" + setNamesToImport.size() + ")");
            jTextAreaOut.insert("\n\nImporting: " + setName, jTextAreaOut.getText().length());
            jTextAreaOut.setCaretPosition(jTextAreaOut.getText().length());
            importOneSet(setName, p);
            jTextAreaOut.insert("\n" + setName + " imported " + mLoadedCardSet.getCards().size() + " cards", jTextAreaOut.getText().length());
            jTextAreaOut.setCaretPosition(jTextAreaOut.getText().length());
            if (jCheckBoxJoin.isSelected()) {
                jTextAreaOut.insert("\nLooking if there is anything to clone...", jTextAreaOut.getText().length());
                jTextAreaOut.setCaretPosition(jTextAreaOut.getText().length());
                int s = seekForKnown(setName);
                allNewKnown += s;
                String dbg = "\n" + setName + " ->" + "Supported Cards found: " + s + " (" + allNewKnown + ")";
                jTextAreaOut.insert(dbg, jTextAreaOut.getText().length());
                jTextAreaOut.setCaretPosition(jTextAreaOut.getText().length());
                System.out.println(dbg);
            }
        }
        String dbg = "\nAll selected sets have been imported.\nDone.";
        jTextAreaOut.insert(dbg, jTextAreaOut.getText().length());
        jTextAreaOut.setCaretPosition(jTextAreaOut.getText().length());
        Configuration.getConfiguration().getLogEntity().addLog(dbg);
    }

    Vector<String> setNamesToImport;

    HashMap<String, Card> map = new HashMap<String, Card>();

    HashMap<String, String> knownSets = new HashMap<String, String>();

    private void generateCardMapForSet(String setName) {
        CardSet cardset = new CardSet();
        cardset.setData(CardSet.getPool().get(setName));
        Vector<Card> cards = cardset.getCards();
        for (int i = 0; i < cards.size(); i++) {
            Card card = cards.elementAt(i);
            map.put(card.getName(), card);
        }
    }

    public int seekForKnown(String newSetName) {
        CardSet cardset = new CardSet();
        cardset.setData(CardSet.getPool().get(newSetName));
        Vector<Card> cards = cardset.getCards();
        int supportedCard = 0;
        for (int i = 0; i < cards.size(); i++) {
            Card newCard = cards.elementAt(i);
            Card knownCard = map.get(newCard.getName());
            if (knownCard == null) {
                if (newCard.isCreature()) {
                    String text = getCleanText(newCard.getText());
                    if (text.length() == 0) {
                        String dbg = "\n" + newCard + " " + newCard.getId() + " as new simple creature supported.";
                        jTextAreaOut.insert(dbg, jTextAreaOut.getText().length());
                        jTextAreaOut.setCaretPosition(jTextAreaOut.getText().length());
                        newCard.setOk("Y");
                        supportedCard++;
                        continue;
                    }
                }
            } else {
                String dbg = "\n" + "Knowncard: " + knownCard + " " + knownCard.getId() + " -> cloning to " + newCard + " " + newCard.getId();
                jTextAreaOut.insert(dbg, jTextAreaOut.getText().length());
                jTextAreaOut.setCaretPosition(jTextAreaOut.getText().length());
                if (knownCard.getType().equals(newCard.getType())) {
                    cloneCard(knownCard, newCard);
                    newCard.setOk(knownCard.getOk());
                    if (knownCard.getOk().equalsIgnoreCase("Y")) supportedCard++;
                    continue;
                }
            }
            newCard.setOk("N");
        }
        cardset.save();
        return supportedCard;
    }

    void cloneCard(Card otherCard, Card mCurrentCard) {
        AIEnhancedCardHints.resetHintPool();
        if (mCurrentCard != null) {
            String basedir = mCurrentCard.getScriptPoolBaseDir();
            File f = new File(csa.Global.mBaseDir + File.separator + basedir);
            if (!f.exists()) {
                boolean b = f.mkdir();
                if (!b) System.out.println("FALSE: " + f.toString());
            }
        }
        ScriptDataPool mScriptDataPool = new ScriptDataPool(mCurrentCard.getScriptPoolBaseName() + ".xml");
        for (int i = 0; i < CardSituation.KEY.length; i++) {
            String scriptForKey = otherCard.getPureScript(CardSituation.KEY[i]);
            ScriptData data = otherCard.getPureScriptData(CardSituation.KEY[i]);
            if (data != null) {
                String script = data.getScript();
                script = csa.util.UtilityString.replace(script, otherCard.getId(), mCurrentCard.getId());
                script = csa.util.UtilityString.replace(script, otherCard.getName(), mCurrentCard.getName());
                data.setScript(script);
                mScriptDataPool.put(data);
            }
        }
        mScriptDataPool.save();
        Configuration.getConfiguration().resetScriptCaching();
        AICardHints otherHints = new AICardHints(otherCard);
        AICardHints myHints = new AICardHints(mCurrentCard);
        for (int i = 0; i < otherHints.size(); i++) {
            AIHintsData otherHint = otherHints.getHintByRow(i);
            AIHintsData aHint = AICardHints.buildNewHint(mCurrentCard);
            aHint.setHintComment(otherHint.getHintComment());
            aHint.setHintName(otherHint.getHintName());
            aHint.setHintValue(otherHint.getHintValue());
            aHint.setSituation(otherHint.getSituation());
            aHint.setHintVarName(otherHint.getHintVarName());
            aHint.setHintVarType(otherHint.getHintVarType());
            aHint.setIsTemplate(false);
            aHint.setCardID(mCurrentCard.getId());
            aHint.setCardSet(mCurrentCard.getSet());
            myHints.addHint(aHint);
        }
        myHints.save();
        AIEnhancedCardHints eotherHints = AIEnhancedCardHints.getHints(otherCard);
        AIEnhancedCardHints emyHints = AIEnhancedCardHints.getHints(mCurrentCard);
        for (int i = 0; i < eotherHints.size(); i++) {
            AIEnhancedHintData otherHint = eotherHints.getHintByRow(i);
            AIEnhancedHintData aHint = AIEnhancedHint.buildNewHint(mCurrentCard);
            aHint.setHintKey(otherHint.getHintKey());
            aHint.setHintNumber(otherHint.getHintNumber());
            aHint.setHintName(otherHint.getHintName());
            aHint.setHintType(otherHint.getHintType());
            aHint.setHintValue(otherHint.getHintValue());
            aHint.setCardID(mCurrentCard.getId());
            aHint.setCardSet(mCurrentCard.getSet());
            emyHints.addHint(aHint);
        }
        emyHints.save();
    }

    String getCleanText(String text) {
        return excludeAbilities(excludeBrackets(text)).trim();
    }

    private String excludeBrackets(String t) {
        while (t.indexOf("(") != -1) {
            int start = t.indexOf("(");
            int end = t.indexOf(")");
            int start2 = t.indexOf("(", start + 1);
            while ((start2 != -1) && (start2 < end)) {
                start = start2;
                start2 = t.indexOf("(", start + 1);
            }
            String t1 = "";
            String t2 = "";
            if (start != 0) t1 = t.substring(0, start);
            if (end < t.length() - 1) t2 = t.substring(end + 1);
            t = t1 + t2;
        }
        return t;
    }

    private String excludeAbilities(String t) {
        String[] abilities = { "Flying", "Haste", "Vigilance", "Defender", "Reach", "Mountainwalk", "Swampwalk", "Forestwalk", "Islandwalk", "Horsemanship" };
        boolean found;
        t = t.trim();
        do {
            found = false;
            for (int i = 0; i < abilities.length; i++) {
                String ability = abilities[i].toUpperCase();
                if (t.toUpperCase().indexOf(ability) == 0) {
                    t = t.substring(ability.length()).trim();
                    if (t.startsWith(",")) t = t.substring(1).trim();
                    if (t.startsWith(":")) t = t.substring(1).trim();
                    found = true;
                    break;
                }
            }
        } while (found);
        return t;
    }

    public void doImport() {
        String klasse = "MagicSets";
        Collection<CardSetData> colC = CardSet.getPool().getMapForKlasse(klasse).values();
        Iterator<CardSetData> iterC = colC.iterator();
        while (iterC.hasNext()) {
            CardSetData item = iterC.next();
            knownSets.put(item.mName, item.mName);
            jTextAreaOut.insert("\n Known set: " + item.mName, jTextAreaOut.getText().length());
            jTextAreaOut.setCaretPosition(jTextAreaOut.getText().length());
            generateCardMapForSet(item.mName);
        }
        setNamesToImport = getSetNames();
        new Thread(ImportSpecialPanel.this).start();
    }
}
