package za.co.data.util;

import za.co.data.framework.modler.ModlerUI;
import java.io.*;

/**
 * Created by Darryl Culverwell
 * On Jun 2, 2008 11:13:05 PM
 */
public class IOUtils {

    /**
     * Grab the contents of the specified file
     *
     * @param file
     * @return
     * @throws IOException
     */
    public static byte[] getFileAsBytes(File file) throws IOException {
        final BufferedInputStream bis = new BufferedInputStream(new FileInputStream(file));
        final byte[] bytes = new byte[(int) file.length()];
        bis.read(bytes);
        bis.close();
        return bytes;
    }

    /**
     * Reads the passed file and returns it as a String
     *
     * @param sourceFile
     * @return
     */
    public static String readSource(File sourceFile) {
        try {
            return new String(getFileAsBytes(sourceFile));
        } catch (IOException e) {
            e.printStackTrace();
        }
        return null;
    }

    /**
     * Copys a file or a folder and it's children
     *
     * @param sourceFile
     * @param destFile
     * @throws IOException
     */
    public static void copyEverything(File sourceFile, File destFile) throws IOException {
        if (sourceFile.isDirectory()) {
            if (!destFile.exists()) destFile.mkdir();
            String[] sourceChildren = sourceFile.list();
            for (int i = 0; i < sourceChildren.length; i++) {
                String s = sourceChildren[i];
                copyEverything(new File(sourceFile, s), new File(destFile, s));
            }
        } else {
            readAndWriteFile(sourceFile, destFile);
        }
    }

    /**
     * Read the content of a file
     */
    private static void readAndWriteFile(File source, File target) {
        try {
            FileInputStream in = new FileInputStream(source);
            FileOutputStream out = new FileOutputStream(target);
            int c;
            while ((c = in.read()) != -1) out.write(c);
            in.close();
            out.close();
        } catch (Exception e) {
        }
    }

    public static void saveProject() {
        try {
            FileOutputStream fos = new FileOutputStream(ModlerUI.instance.getDataSiloPref());
            ModlerUI.instance.properties.store(fos, "Generated by DataSiloModler. Do not edit ");
            fos.flush();
            fos.close();
        } catch (Exception ex) {
        }
    }
}
