package gui;

import java.util.*;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import logica.*;
import java.io.*;
import java.nio.channels.FileChannel;
import accesoDatos.*;

/**
 *
 * @author Gamboa Family
 */
public class PanelResultadosConsulta extends javax.swing.JPanel implements ItemListener {

    Vector<Material> resultados;

    Vector<JPanel> panelInfoMaterial, panelPrincipal;

    Vector<JLabel> LTituloPri, tituloPri, LTituloSec, tituloSec, LAutor, autor;

    Vector<JRadioButton> radioBotones;

    ButtonGroup grupoRadioBot;

    JTextField jTextField;

    String rutaDestinoDescarga, codigoUsuario;

    Boolean rutaEscogida;

    int panelActual, materialSelccionado;

    /** Creates new form PanelResulatdosConsulta */
    public PanelResultadosConsulta() {
        initComponents();
        jBDescargar.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void mostrarResulatdos(Vector<Material> results, JTextField textField) {
        this.resultados = results;
        this.jTextField = textField;
        instanciarVectores();
        for (int k = 0; k < (resultados.size() / 5) + 1; k++) {
            JPanel principalAux = new JPanel(null);
            principalAux.setBounds(0, 0, 1020, 5 * 91);
            principalAux.setBackground(Color.WHITE);
            int m = 0;
            for (int i = k * 5; i < 5 * (k + 1) && i < resultados.size(); i++) {
                instanciarElementos(i);
                agregarElementosAPaneles(i, m);
                principalAux.add(panelInfoMaterial.elementAt(i));
                m++;
            }
            m = 0;
            panelPrincipal.add(k, principalAux);
        }
        jPanel3.setLayout(null);
        panelActual = 0;
        jPanel3.add(panelPrincipal.firstElement());
        jPanel3.setBounds(0, 0, 1016, 5 * 91);
        if (panelPrincipal.size() == 1) jButton3.setEnabled(false);
        this.setBounds(0, 0, 1030, 510);
    }

    public Vector retornarPaneles() {
        return panelPrincipal;
    }

    private void initComponents() {
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jBDescargar = new javax.swing.JButton();
        jBConsultar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 990, Short.MAX_VALUE));
        jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 324, Short.MAX_VALUE));
        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Verdana", 1, 14));
        jButton2.setForeground(new java.awt.Color(235, 30, 30));
        jButton2.setText("Ver Mas Información");
        jButton2.setToolTipText("Escoja un documento de la lista y presione para ver mas informacion acera del mismo.");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Verdana", 1, 14));
        jButton3.setForeground(new java.awt.Color(235, 30, 30));
        jButton3.setText(">");
        jButton3.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Verdana", 1, 14));
        jButton5.setForeground(new java.awt.Color(235, 30, 30));
        jButton5.setText("<");
        jButton5.setEnabled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup().addContainerGap(900, Short.MAX_VALUE).addComponent(jButton5).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jButton3).addContainerGap()));
        jPanel5Layout.setVerticalGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jButton3).addComponent(jButton5)));
        jBDescargar.setBackground(new java.awt.Color(255, 255, 255));
        jBDescargar.setFont(new java.awt.Font("Verdana", 1, 14));
        jBDescargar.setForeground(new java.awt.Color(235, 30, 30));
        jBDescargar.setText("Descargar");
        jBDescargar.setToolTipText("Escoja un documento de la lista y presione para ver mas informacion acera del mismo.");
        jBDescargar.setEnabled(false);
        jBDescargar.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDescargarActionPerformed(evt);
            }
        });
        jBConsultar.setBackground(new java.awt.Color(255, 255, 255));
        jBConsultar.setFont(new java.awt.Font("Verdana", 1, 14));
        jBConsultar.setForeground(new java.awt.Color(235, 30, 30));
        jBConsultar.setText("Cosultar");
        jBConsultar.setToolTipText("Escoja un documento de la lista y presione para ver mas informacion acera del mismo.");
        jBConsultar.setEnabled(false);
        jBConsultar.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultarActionPerformed(evt);
            }
        });
        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel4Layout.createSequentialGroup().addComponent(jButton2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jBConsultar).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jBDescargar).addGap(615, 615, 615)).addGroup(jPanel4Layout.createSequentialGroup().addGap(12, 12, 12).addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup().addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE).addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jButton2).addComponent(jBConsultar).addComponent(jBDescargar))));
        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 22));
        jLabel1.setForeground(new java.awt.Color(235, 30, 30));
        jLabel1.setText("Resultados de la Consulta");
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel1Layout.createSequentialGroup().addGap(303, 303, 303).addComponent(jLabel1).addContainerGap(340, Short.MAX_VALUE)));
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup().addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(jLabel1).addContainerGap()));
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addContainerGap()).addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addContainerGap()));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup().addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)));
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        Vector<Autor> autores = resultados.elementAt(materialSelccionado).getAutores();
        String cadenaAutores = "";
        for (int j = 0; j < autores.size(); j++) {
            cadenaAutores += autores.elementAt(j).getNombreCompleto() + ", ";
        }
        JTextArea areaInfo = new JTextArea(20, 40);
        areaInfo.setText("\n\nCODIGO: " + resultados.elementAt(materialSelccionado).getCodigo() + "\n\nTITULO PRINCIPAL: " + resultados.elementAt(materialSelccionado).getTitulo_pri() + "\n\nTITULO SECUNDARIO: " + resultados.elementAt(materialSelccionado).getTitulo_sec() + "\n\nAUTORES: " + cadenaAutores + "\n\nFECHA DE CREACION: " + resultados.elementAt(materialSelccionado).getFecha_creacion() + "\n\nFECHA DE PUBLICACION: " + resultados.elementAt(materialSelccionado).getFecha_publicacion() + "\n\nIDIOMA: " + resultados.elementAt(materialSelccionado).getIdioma() + "\n\nFORMATO: " + resultados.elementAt(materialSelccionado).getFormato() + "\n\nEDITORIAL: " + resultados.elementAt(materialSelccionado).getEditorial() + "\n\nDESCRIPCION: " + resultados.elementAt(materialSelccionado).getDescripcion() + "\n\nTIPO DE MATERIAL: " + resultados.elementAt(materialSelccionado).getTipo_mat().getNombre());
        areaInfo.setWrapStyleWord(true);
        areaInfo.setLineWrap(true);
        JScrollPane scroll = new JScrollPane(areaInfo);
        JOptionPane.showMessageDialog(this, scroll, "INFORMACION DETALLADA DEL MATERIAL", JOptionPane.INFORMATION_MESSAGE);
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
        panelActual++;
        jPanel3.removeAll();
        jPanel3.add(panelPrincipal.elementAt(panelActual));
        if (panelActual == panelPrincipal.size() - 1) jButton3.setEnabled(false);
        if (panelActual > 0) jButton5.setEnabled(true);
        this.validate();
        this.repaint();
    }

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
        panelActual--;
        jPanel3.removeAll();
        jPanel3.add(panelPrincipal.elementAt(panelActual));
        if (panelActual == 0) jButton5.setEnabled(false);
        if (panelActual < panelPrincipal.size()) jButton3.setEnabled(true);
        this.validate();
        this.repaint();
    }

    private void jBDescargarActionPerformed(java.awt.event.ActionEvent evt) {
        escogerRutaDestino();
        if (rutaEscogida) {
            descargarArchivo();
            DaoDescargaUsuario dao = new DaoDescargaUsuario();
            Calendar calendario = Calendar.getInstance();
            Calendar gregCalendario = new GregorianCalendar();
            String fecha = Integer.toString(gregCalendario.get(Calendar.YEAR)) + "-" + Integer.toString(gregCalendario.get(Calendar.MONTH)) + "-" + Integer.toString(gregCalendario.get(Calendar.DATE));
            String hora = String.valueOf(gregCalendario.get(Calendar.HOUR_OF_DAY));
            String codMaterial = resultados.elementAt(materialSelccionado).getCodigo();
            dao.guardarConsultaUsuario(codigoUsuario, codMaterial, fecha, hora);
        }
    }

    private void jBConsultarActionPerformed(java.awt.event.ActionEvent evt) {
        boolean visualizado = false;
        if (resultados.elementAt(materialSelccionado).getFormato().equals("pdf") || resultados.elementAt(materialSelccionado).getFormato().equals("PDF")) {
            visualizadorPdf visualizador = new visualizadorPdf(resultados.elementAt(materialSelccionado).getRuta());
            visualizado = true;
        }
        if (resultados.elementAt(materialSelccionado).getFormato().equals("jpg") || resultados.elementAt(materialSelccionado).getFormato().equals("JPG") || resultados.elementAt(materialSelccionado).getFormato().equals("jpeg") || resultados.elementAt(materialSelccionado).getFormato().equals("JPEG")) {
            visualizadorJPG visualizador = new visualizadorJPG(resultados.elementAt(materialSelccionado).getRuta());
            visualizado = true;
        }
        if (visualizado) {
            DaoCosultaUsuario dao = new DaoCosultaUsuario();
            Calendar calendario = Calendar.getInstance();
            Calendar gregCalendario = new GregorianCalendar();
            String fecha = Integer.toString(gregCalendario.get(Calendar.YEAR)) + "-" + Integer.toString(gregCalendario.get(Calendar.MONTH)) + "-" + Integer.toString(gregCalendario.get(Calendar.DATE));
            String hora = Integer.toString(gregCalendario.get(Calendar.HOUR)) + ":" + Integer.toString(gregCalendario.get(Calendar.MINUTE)) + ":" + Integer.toString(gregCalendario.get(Calendar.SECOND));
            String codMaterial = resultados.elementAt(materialSelccionado).getCodigo();
            dao.guardarConsultaUsuario(codigoUsuario, codMaterial, fecha, hora);
        }
        if (!visualizado) JOptionPane.showMessageDialog(this, "El formato en el que se encuentra el archivo " + "no está soportado.", "Formato no Soportado", JOptionPane.ERROR_MESSAGE);
    }

    public void itemStateChanged(ItemEvent e) {
        for (int i = 0; i < radioBotones.size(); i++) {
            if (e.getSource() == radioBotones.elementAt(i)) {
                materialSelccionado = i;
                jButton2.setEnabled(true);
                jBDescargar.setEnabled(true);
                jBConsultar.setEnabled(true);
            }
        }
    }

    public void instanciarVectores() {
        panelInfoMaterial = new Vector();
        LTituloPri = new Vector();
        tituloPri = new Vector();
        LTituloSec = new Vector();
        tituloSec = new Vector();
        LAutor = new Vector();
        autor = new Vector();
        radioBotones = new Vector();
        grupoRadioBot = new ButtonGroup();
        panelPrincipal = new Vector();
    }

    public void instanciarElementos(int i) {
        JLabel tit_pri = new JLabel("Titulo Principal: ");
        tit_pri.setFont(new Font("Verdana", Font.BOLD, 13));
        tit_pri.setForeground(new Color(130, 134, 135));
        LTituloPri.add(i, tit_pri);
        JLabel tit_sec = new JLabel("Titulo Secundario: ");
        tit_sec.setFont(new Font("Verdana", Font.BOLD, 13));
        tit_sec.setForeground(new Color(130, 134, 135));
        LTituloSec.add(i, tit_sec);
        JLabel aut = new JLabel("Autor: ");
        aut.setFont(new Font("Verdana", Font.BOLD, 13));
        aut.setForeground(new Color(130, 134, 135));
        LAutor.add(i, aut);
        tituloPri.add(i, new JLabel(resultados.elementAt(i).getTitulo_pri()));
        tituloSec.add(i, new JLabel(resultados.elementAt(i).getTitulo_sec()));
        Vector<Autor> autores = resultados.elementAt(i).getAutores();
        String cadenaAutores = "";
        for (int j = 0; j < autores.size(); j++) {
            cadenaAutores += autores.elementAt(j).getNombreCompleto() + ", ";
        }
        autor.add(i, new JLabel(cadenaAutores));
        radioBotones.add(i, new JRadioButton());
        grupoRadioBot.add(radioBotones.elementAt(i));
    }

    public void agregarElementosAPaneles(int i, int m) {
        JPanel panelTemporal = new JPanel(null);
        panelTemporal.setBounds(3, (75 * m) + 5, 1015, 70);
        panelTemporal.setBorder(BorderFactory.createLineBorder(new Color(235, 30, 30)));
        panelTemporal.setBackground(Color.WHITE);
        panelTemporal.add(radioBotones.elementAt(i));
        radioBotones.elementAt(i).setBounds(5, 25, 20, 20);
        radioBotones.elementAt(i).setBackground(Color.WHITE);
        radioBotones.elementAt(i).addItemListener(this);
        panelTemporal.add(LTituloPri.elementAt(i));
        LTituloPri.elementAt(i).setBounds(30, 5, 130, 20);
        panelTemporal.add(LTituloSec.elementAt(i));
        LTituloSec.elementAt(i).setBounds(30, 25, 140, 20);
        panelTemporal.add(LAutor.elementAt(i));
        LAutor.elementAt(i).setBounds(30, 45, 50, 20);
        panelTemporal.add(tituloPri.elementAt(i));
        tituloPri.elementAt(i).setBounds(145, 7, 600, 20);
        panelTemporal.add(tituloSec.elementAt(i));
        tituloSec.elementAt(i).setBounds(165, 27, 600, 20);
        panelTemporal.add(autor.elementAt(i));
        autor.elementAt(i).setBounds(80, 47, 600, 20);
        panelInfoMaterial.add(i, panelTemporal);
    }

    public void escogerRutaDestino() {
        JFileChooser escogerRuta = new JFileChooser();
        escogerRuta.addChoosableFileFilter(new FiltroFormatosMateriales());
        escogerRuta.setFileFilter(escogerRuta.getChoosableFileFilters()[1]);
        int opcion = escogerRuta.showSaveDialog(this);
        if (opcion == JFileChooser.APPROVE_OPTION) {
            rutaDestinoDescarga = escogerRuta.getSelectedFile().getPath();
            rutaEscogida = true;
        } else {
            JOptionPane.showMessageDialog(this, "Eliga la carpeta de destino para guardar el Material.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            rutaEscogida = false;
        }
    }

    public void descargarArchivo() {
        try {
            FileInputStream fis = new FileInputStream(resultados.elementAt(materialSelccionado).getRuta());
            FileOutputStream fos = new FileOutputStream(rutaDestinoDescarga);
            FileChannel inChannel = fis.getChannel();
            FileChannel outChannel = fos.getChannel();
            inChannel.transferTo(0, inChannel.size(), outChannel);
            fis.close();
            fos.close();
        } catch (IOException ioe) {
            System.err.println("Error al Generar Copia del Material\n" + ioe);
        }
    }

    public void habilitarDescarga() {
        jBDescargar.setVisible(true);
    }

    public void setUsuarioQueConsulta(String codigoUsr) {
        codigoUsuario = codigoUsr;
    }

    private javax.swing.JButton jBConsultar;

    private javax.swing.JButton jBDescargar;

    private javax.swing.JButton jButton2;

    private javax.swing.JButton jButton3;

    private javax.swing.JButton jButton5;

    private javax.swing.JLabel jLabel1;

    private javax.swing.JPanel jPanel1;

    private javax.swing.JPanel jPanel3;

    private javax.swing.JPanel jPanel4;

    private javax.swing.JPanel jPanel5;
}
