package org.wwweeeportal.portal.channelplugins;

import java.util.*;
import org.w3c.dom.*;
import org.wwweeeportal.util.xml.dom.*;
import org.wwweeeportal.util.xml.html.*;
import org.wwweeeportal.portal.*;

/**
 * <p>
 * A {@link org.wwweeeportal.portal.Channel.Plugin Plugin} providing a channel {@linkplain AbstractChannelAugmentation
 * augmentation} for rendering the channel {@linkplain org.wwweeeportal.portal.Channel.ViewResponse#getTitle() title}.
 * </p>
 * 
 * <p>
 * By default, XHTML with the following general structure will be generated...
 * </p>
 * 
 * <p>
 * <code>
 * &lt;{@link #TITLE_ELEMENT_NAME_PROP h2}&gt;&lt;a {@link #TITLE_ANCHOR_HREF_PROP href}=&quot;___&quot; {@link #TITLE_ANCHOR_TITLE_PROP title}=&quot;___&quot; {@link #TITLE_ANCHOR_REL_PROP rel}=&quot;___&quot;&gt;&lt;span&gt;{@linkplain org.wwweeeportal.portal.Channel.ViewResponse#getTitle() Channel Title}&lt;/span&gt;&lt;/a&gt;&lt;/{@link #TITLE_ELEMENT_NAME_PROP h2}&gt;
 * </code>
 * </p>
 * 
 * <h3 id="configuration">Configuration</h3>
 * <p>
 * In addition to those inherited from the {@link AbstractChannelAugmentation} class, the following
 * {@linkplain ConfigManager configuration properties} are supported by this class:
 * </p>
 * <ul>
 * <li>{@link #TITLE_ELEMENT_NAME_PROP}</li>
 * <li>{@link #TITLE_ANCHOR_HREF_PROP}</li>
 * <li>{@link #TITLE_ANCHOR_TITLE_PROP}</li>
 * <li>{@link #TITLE_ANCHOR_REL_PROP}</li>
 * </ul>
 */
public class ChannelTitle extends AbstractChannelAugmentation {

    /**
   * <p>
   * The key to a {@link org.wwweeeportal.util.ws.rs.RSProperties#RESULT_STRING_CONVERTER String} property defining the
   * {@linkplain Element#getLocalName() local name} for the {@linkplain HTMLUtil#HTML_NS_URI HTML} {@link Element}
   * created to house the title.
   * </p>
   * 
   * <p>
   * This defaults to using an <code>&lt;h2&gt;</code> element for each channel (assuming it will be second to the
   * <code>&lt;h1&gt;</code> generated by the {@link org.wwweeeportal.portal.channels.PageHeadingChannel
   * PageHeadingChannel}).
   * </p>
   * 
   * <p>
   * Also keep in mind that you are able to set this property globally within the root
   * {@link WWWeeePortal#getProperties() portal properties}, where it will automatically apply to <em>all</em> instances
   * of this plugin by default, but can still be overridden on a per-instance basis.
   * </p>
   * 
   * @see #createAugmentationContent(Page.Request, Channel.ViewResponse, Element)
   * @category WWWEEE_PORTAL_CONFIG_PROP
   */
    public static final String TITLE_ELEMENT_NAME_PROP = "Channel.Title.ElementName";

    /**
   * The key to a {@link org.wwweeeportal.util.ws.rs.RSProperties#RESULT_STRING_CONVERTER String} property specifying
   * the value of an <code>&quot;href&quot;</code> {@link Attr attribute} to be included on the anchor (
   * <code>&lt;a&gt;</code>) element generated by this plugin.
   * 
   * @see #createAugmentationContent(Page.Request, Channel.ViewResponse, Element)
   * @category WWWEEE_PORTAL_CONFIG_PROP
   */
    public static final String TITLE_ANCHOR_HREF_PROP = "Channel.Title.Anchor.Href";

    /**
   * The key to a {@link org.wwweeeportal.util.ws.rs.RSProperties#RESULT_STRING_CONVERTER String} property specifying
   * the value of a <code>&quot;title&quot;</code> {@link Attr attribute} to be included on the anchor (
   * <code>&lt;a&gt;</code>) element generated by this plugin.
   * 
   * @see #createAugmentationContent(Page.Request, Channel.ViewResponse, Element)
   * @category WWWEEE_PORTAL_CONFIG_PROP
   */
    public static final String TITLE_ANCHOR_TITLE_PROP = "Channel.Title.Anchor.Title";

    /**
   * The key to a {@link org.wwweeeportal.util.ws.rs.RSProperties#RESULT_STRING_CONVERTER String} property specifying
   * the value of a <code>&quot;rel&quot;</code> {@link Attr attribute} to be included on the anchor (
   * <code>&lt;a&gt;</code>) element generated by this plugin.
   * 
   * @see #createAugmentationContent(Page.Request, Channel.ViewResponse, Element)
   * @category WWWEEE_PORTAL_CONFIG_PROP
   */
    public static final String TITLE_ANCHOR_REL_PROP = "Channel.Title.Anchor.Rel";

    /**
   * Construct a new <code>ChannelTitle</code> instance.
   */
    public ChannelTitle(final Channel channel, final ContentManager.ChannelPluginDefinition<?> definition) throws WWWeeePortal.Exception {
        super(channel, definition);
        return;
    }

    @Override
    protected void createAugmentationContent(final Page.Request pageRequest, final Channel.ViewResponse viewResponse, final Element augmentationElement) throws WWWeeePortal.Exception {
        final Element titleElement = DOMUtil.createElement(HTMLUtil.HTML_NS_URI, HTMLUtil.HTML_NS_PREFIX, getConfigProp(TITLE_ELEMENT_NAME_PROP, pageRequest, "h2", false), augmentationElement);
        getChannel().setIDAndClassAttrs(titleElement, Arrays.asList("title"), null, null);
        final Element titleAnchorElement = DOMUtil.createElement(HTMLUtil.HTML_NS_URI, HTMLUtil.HTML_NS_PREFIX, "a", titleElement);
        getChannel().setIDAndClassAttrs(titleAnchorElement, Arrays.asList("title", "anchor"), null, null);
        final Element titleTextElement = DOMUtil.createElement(HTMLUtil.HTML_NS_URI, HTMLUtil.HTML_NS_PREFIX, "span", titleAnchorElement);
        getChannel().setIDAndClassAttrs(titleTextElement, Arrays.asList("title", "text"), null, null);
        DOMUtil.appendText(titleTextElement, viewResponse.getTitle());
        final String titleAnchorHrefProp = getConfigProp(TITLE_ANCHOR_HREF_PROP, pageRequest, null, true);
        if (titleAnchorHrefProp != null) DOMUtil.createAttribute(null, null, "href", titleAnchorHrefProp, titleAnchorElement);
        final String titleAnchorTitleProp = getConfigProp(TITLE_ANCHOR_TITLE_PROP, pageRequest, null, true);
        if (titleAnchorTitleProp != null) DOMUtil.createAttribute(null, null, "title", titleAnchorTitleProp, titleAnchorElement);
        final String titleAnchorRelProp = getConfigProp(TITLE_ANCHOR_REL_PROP, pageRequest, null, true);
        if (titleAnchorRelProp != null) DOMUtil.createAttribute(null, null, "rel", titleAnchorRelProp, titleAnchorElement);
        return;
    }
}
