package org.omg.CosNotifyChannelAdmin;

/**
* org/omg/CosNotifyChannelAdmin/ConnectionAlreadyInactiveHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNotifyChannelAdmin.idl
* Friday, December 17, 2004 1:02:16 PM EST
*/
public final class ConnectionAlreadyInactiveHolder implements org.omg.CORBA.portable.Streamable {

    public org.omg.CosNotifyChannelAdmin.ConnectionAlreadyInactive value = null;

    public ConnectionAlreadyInactiveHolder() {
    }

    public ConnectionAlreadyInactiveHolder(org.omg.CosNotifyChannelAdmin.ConnectionAlreadyInactive initialValue) {
        value = initialValue;
    }

    public void _read(org.omg.CORBA.portable.InputStream i) {
        value = org.omg.CosNotifyChannelAdmin.ConnectionAlreadyInactiveHelper.read(i);
    }

    public void _write(org.omg.CORBA.portable.OutputStream o) {
        org.omg.CosNotifyChannelAdmin.ConnectionAlreadyInactiveHelper.write(o, value);
    }

    public org.omg.CORBA.TypeCode _type() {
        return org.omg.CosNotifyChannelAdmin.ConnectionAlreadyInactiveHelper.type();
    }
}
